In [1]:
import pandas as pd   
import numpy as np 
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
foodimports=pd.read_excel('../data/FoodImports.xlsx', sheet_name='FoodVolume', header=None)
foodimports

,0,1,2,3,4,5,6,7,8,9,...,17,18,19,20,21,22,23,24,25,26
0,"U.S. food import volume, by food group",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Food group,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,2022.0,2021.0,2020.0,2019.0,2018.0,2017.0,2016.0,...,2008.0,2007.0,2006.0,2005.0,2004.0,2003.0,2002.0,2001.0,2000.0,1999.0
4,Foods 1/,Live meat animals 2/,"1,000",8135.1,8440.5,7397.3,7139.2,7124.5,7363.3,7336.2,...,11558.6,12419.5,10985.5,9951.9,9866.3,9223.2,8302.9,7758.1,6521.8,6058.4
5,NaN,Meats,"1,000 mt",2194.4,2077.5,1886.9,1795.5,1821.2,1847.8,1824.8,...,1411.4,1628.2,1627.4,1797.1,1839.2,1659.3,1700.0,1634.0,1578.1,1439.6
6,NaN,Fish and shellfish 3/,"1,000 mt",3158.7,3111.5,2778.2,2704.9,2773.4,2669.9,2585.0,...,2254.5,2288.1,2317.1,2199.5,2119.9,2082.4,1903.5,1759.0,1717.2,1689.8
7,NaN,Dairy,"1,000 mt",407.2,396.7,392.8,408.1,379.9,382.3,395.6,...,309.8,370.8,375.6,382.4,346.4,339.0,332.8,326.7,298.9,299.2
8,NaN,Vegetables,"1,000 mt",12100.7,13349.0,12278.7,11763.4,11663.0,11070.2,10588.4,...,7348.8,7204.5,6616.6,6368.6,6245.5,5967.2,5584.6,5139.6,4755.4,4790.1
9,NaN,Fruits 4/,"1,000 mt",15308.3,14768.3,14168.0,13882.4,14017.0,13606.2,13249.5,...,9782.5,9933.5,9111.9,8757.5,8428.6,8288.9,8006.7,7556.8,7688.5,7870.2
10,NaN,Nuts,"1,000 mt",552.4,592.9,523.4,543.0,558.4,550.8,517.9,...,344.2,360.6,326.5,326.7,336.7,317.9,383.2,374.4,364.0,318.9
11,NaN,"Coffee, tea, and spices","1,000 mt",2414.0,2344.5,2254.6,2371.9,2236.8,2276.2,2235.8,...,1881.9,1850.9,1827.4,1746.3,1758.7,1716.3,1636.5,1600.9,1726.1,1651.5
12,NaN,Grains,"1,000 mt",12586.6,11319.0,11799.4,11464.7,12212.8,11854.3,10994.5,...,9798.4,8888.4,7832.8,6694.6,6643.2,6221.3,7031.6,7435.5,6627.6,6985.1
13,NaN,Vegetable oils,"1,000 mt",7192.3,6718.8,6219.9,6149.8,6281.9,6399.9,6198.2,...,4839.0,3930.4,3576.7,2869.0,2759.4,2066.7,2380.2,2803.1,2802.1,2428.0
14,NaN,Sugar and candy,"1,000 mt",4900.0,4538.8,4957.3,4304.9,4193.2,4111.9,4374.7,...,3666.1,2985.5,3916.2,3125.6,2433.1,2416.7,2193.6,2085.7,2159.0,2269.3
15,NaN,Cocoa and chocolate,"1,000 mt",1514.7,1532.5,1391.9,1393.9,1372.9,1454.2,1365.8,...,1114.2,1129.2,1255.6,1308.1,1170.3,1048.5,918.6,993.1,1001.2,924.7
16,NaN,Other edible products 5/,"1,000 mt",4338.0,3079.1,2689.8,2437.6,2420.6,2250.1,2432.7,...,2080.3,1996.9,1955.3,1832.5,1750.1,1532.9,1502.9,1403.4,1168.1,1099.2
17,NaN,Beverages 6/,"1,000 litpf",7399.4,10006.7,8943.1,8336.4,8224.2,8234.0,7181.2,...,5439.9,5605.1,5461.8,4790.1,4387.6,4205.7,3981.8,3701.3,3383.9,2974.1
18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,1/ Import volumes are obtained by HS-4 or 6 co...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,"2/ Number of food animals, except fowl.",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,3/ Includes prepared fish 1604 and 1605.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,4/ Excludes fruit juices.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,5/ Excludes vinegar measured in kiloliters.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,6/ Includes liquors.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,mt = metric tons.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,"Source: U.S. Department of Commerce, Bureau of...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
#changed rows to columns
df_1 =foodimports.transpose()
df_1

,0,1,2,3,4,5,6,7,8,9,...,17,18,19,20,21,22,23,24,25,26
0,"U.S. food import volume, by food group",NaN,Food group,NaN,Foods 1/,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,1/ Import volumes are obtained by HS-4 or 6 co...,"2/ Number of food animals, except fowl.",3/ Includes prepared fish 1604 and 1605.,4/ Excludes fruit juices.,5/ Excludes vinegar measured in kiloliters.,6/ Includes liquors.,mt = metric tons.,"Source: U.S. Department of Commerce, Bureau of..."
1,NaN,NaN,NaN,NaN,Live meat animals 2/,Meats,Fish and shellfish 3/,Dairy,Vegetables,Fruits 4/,...,Beverages 6/,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,"1,000","1,000 mt","1,000 mt","1,000 mt","1,000 mt","1,000 mt",...,"1,000 litpf",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,2022.0,8135.1,2194.4,3158.7,407.2,12100.7,15308.3,...,7399.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,2021.0,8440.5,2077.5,3111.5,396.7,13349.0,14768.3,...,10006.7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,2020.0,7397.3,1886.9,2778.2,392.8,12278.7,14168.0,...,8943.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,NaN,NaN,2019.0,7139.2,1795.5,2704.9,408.1,11763.4,13882.4,...,8336.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,NaN,NaN,2018.0,7124.5,1821.2,2773.4,379.9,11663.0,14017.0,...,8224.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,NaN,NaN,NaN,2017.0,7363.3,1847.8,2669.9,382.3,11070.2,13606.2,...,8234.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,NaN,NaN,2016.0,7336.2,1824.8,2585.0,395.6,10588.4,13249.5,...,7181.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,NaN,NaN,NaN,2015.0,7661.2,1942.8,2525.0,359.3,9733.1,12861.1,...,6721.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,NaN,NaN,NaN,2014.0,7232.6,1720.2,2474.2,302.5,9574.5,12161.7,...,6226.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,NaN,NaN,NaN,2013.0,6947.3,1400.5,2399.7,293.6,8989.3,11833.3,...,5946.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,NaN,NaN,NaN,2012.0,7909.8,1336.6,2384.4,292.0,8628.1,11031.8,...,5991.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,NaN,NaN,NaN,2011.0,7872.7,1270.1,2349.4,248.6,8440.9,10466.4,...,5563.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,NaN,NaN,NaN,2010.0,7997.6,1371.5,2345.0,249.7,8087.0,10148.8,...,5348.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,NaN,NaN,NaN,2009.0,8350.0,1445.4,2248.8,289.4,7312.6,9495.2,...,5088.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,NaN,NaN,NaN,2008.0,11558.6,1411.4,2254.5,309.8,7348.8,9782.5,...,5439.9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,NaN,NaN,NaN,2007.0,12419.5,1628.2,2288.1,370.8,7204.5,9933.5,...,5605.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,NaN,NaN,NaN,2006.0,10985.5,1627.4,2317.1,375.6,6616.6,9111.9,...,5461.8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,NaN,NaN,NaN,2005.0,9951.9,1797.1,2199.5,382.4,6368.6,8757.5,...,4790.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,NaN,NaN,NaN,2004.0,9866.3,1839.2,2119.9,346.4,6245.5,8428.6,...,4387.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,NaN,NaN,NaN,2003.0,9223.2,1659.3,2082.4,339.0,5967.2,8288.9,...,4205.7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,NaN,NaN,NaN,2002.0,8302.9,1700.0,1903.5,332.8,5584.6,8006.7,...,3981.8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,NaN,NaN,NaN,2001.0,7758.1,1634.0,1759.0,326.7,5139.6,7556.8,...,3701.3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,NaN,NaN,NaN,2000.0,6521.8,1578.1,1717.2,298.9,4755.4,7688.5,...,3383.9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,NaN,NaN,NaN,1999.0,6058.4,1439.6,1689.8,299.2,4790.1,7870.2,...,2974.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
df_1.drop(columns=df_1.columns[[0, 1, 2]], inplace=True)
df_1

,3,4,5,6,7,8,9,10,11,12,...,17,18,19,20,21,22,23,24,25,26
0,NaN,Foods 1/,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,1/ Import volumes are obtained by HS-4 or 6 co...,"2/ Number of food animals, except fowl.",3/ Includes prepared fish 1604 and 1605.,4/ Excludes fruit juices.,5/ Excludes vinegar measured in kiloliters.,6/ Includes liquors.,mt = metric tons.,"Source: U.S. Department of Commerce, Bureau of..."
1,NaN,Live meat animals 2/,Meats,Fish and shellfish 3/,Dairy,Vegetables,Fruits 4/,Nuts,"Coffee, tea, and spices",Grains,...,Beverages 6/,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,"1,000","1,000 mt","1,000 mt","1,000 mt","1,000 mt","1,000 mt","1,000 mt","1,000 mt","1,000 mt",...,"1,000 litpf",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2022.0,8135.1,2194.4,3158.7,407.2,12100.7,15308.3,552.4,2414.0,12586.6,...,7399.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2021.0,8440.5,2077.5,3111.5,396.7,13349.0,14768.3,592.9,2344.5,11319.0,...,10006.7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,2020.0,7397.3,1886.9,2778.2,392.8,12278.7,14168.0,523.4,2254.6,11799.4,...,8943.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,2019.0,7139.2,1795.5,2704.9,408.1,11763.4,13882.4,543.0,2371.9,11464.7,...,8336.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,2018.0,7124.5,1821.2,2773.4,379.9,11663.0,14017.0,558.4,2236.8,12212.8,...,8224.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,2017.0,7363.3,1847.8,2669.9,382.3,11070.2,13606.2,550.8,2276.2,11854.3,...,8234.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,2016.0,7336.2,1824.8,2585.0,395.6,10588.4,13249.5,517.9,2235.8,10994.5,...,7181.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,2015.0,7661.2,1942.8,2525.0,359.3,9733.1,12861.1,510.5,2161.0,10991.5,...,6721.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,2014.0,7232.6,1720.2,2474.2,302.5,9574.5,12161.7,476.2,2112.4,11364.5,...,6226.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,2013.0,6947.3,1400.5,2399.7,293.6,8989.3,11833.3,433.6,2087.0,13034.1,...,5946.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,2012.0,7909.8,1336.6,2384.4,292.0,8628.1,11031.8,478.0,2018.8,10689.8,...,5991.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,2011.0,7872.7,1270.1,2349.4,248.6,8440.9,10466.4,368.7,2015.0,8586.8,...,5563.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,2010.0,7997.6,1371.5,2345.0,249.7,8087.0,10148.8,363.5,1894.6,8643.0,...,5348.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,2009.0,8350.0,1445.4,2248.8,289.4,7312.6,9495.2,362.1,1823.0,8816.3,...,5088.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,2008.0,11558.6,1411.4,2254.5,309.8,7348.8,9782.5,344.2,1881.9,9798.4,...,5439.9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,2007.0,12419.5,1628.2,2288.1,370.8,7204.5,9933.5,360.6,1850.9,8888.4,...,5605.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,2006.0,10985.5,1627.4,2317.1,375.6,6616.6,9111.9,326.5,1827.4,7832.8,...,5461.8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,2005.0,9951.9,1797.1,2199.5,382.4,6368.6,8757.5,326.7,1746.3,6694.6,...,4790.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,2004.0,9866.3,1839.2,2119.9,346.4,6245.5,8428.6,336.7,1758.7,6643.2,...,4387.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,2003.0,9223.2,1659.3,2082.4,339.0,5967.2,8288.9,317.9,1716.3,6221.3,...,4205.7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,2002.0,8302.9,1700.0,1903.5,332.8,5584.6,8006.7,383.2,1636.5,7031.6,...,3981.8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,2001.0,7758.1,1634.0,1759.0,326.7,5139.6,7556.8,374.4,1600.9,7435.5,...,3701.3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,2000.0,6521.8,1578.1,1717.2,298.9,4755.4,7688.5,364.0,1726.1,6627.6,...,3383.9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,1999.0,6058.4,1439.6,1689.8,299.2,4790.1,7870.2,318.9,1651.5,6985.1,...,2974.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
 df_2 = df_1.drop(labels=[0,1,2], axis=0)
df_2

,3,4,5,6,7,8,9,10,11,12,...,17,18,19,20,21,22,23,24,25,26
3,2022.0,8135.1,2194.4,3158.7,407.2,12100.7,15308.3,552.4,2414.0,12586.6,...,7399.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2021.0,8440.5,2077.5,3111.5,396.7,13349.0,14768.3,592.9,2344.5,11319.0,...,10006.7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,2020.0,7397.3,1886.9,2778.2,392.8,12278.7,14168.0,523.4,2254.6,11799.4,...,8943.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,2019.0,7139.2,1795.5,2704.9,408.1,11763.4,13882.4,543.0,2371.9,11464.7,...,8336.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,2018.0,7124.5,1821.2,2773.4,379.9,11663.0,14017.0,558.4,2236.8,12212.8,...,8224.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,2017.0,7363.3,1847.8,2669.9,382.3,11070.2,13606.2,550.8,2276.2,11854.3,...,8234.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,2016.0,7336.2,1824.8,2585.0,395.6,10588.4,13249.5,517.9,2235.8,10994.5,...,7181.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,2015.0,7661.2,1942.8,2525.0,359.3,9733.1,12861.1,510.5,2161.0,10991.5,...,6721.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,2014.0,7232.6,1720.2,2474.2,302.5,9574.5,12161.7,476.2,2112.4,11364.5,...,6226.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,2013.0,6947.3,1400.5,2399.7,293.6,8989.3,11833.3,433.6,2087.0,13034.1,...,5946.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,2012.0,7909.8,1336.6,2384.4,292.0,8628.1,11031.8,478.0,2018.8,10689.8,...,5991.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,2011.0,7872.7,1270.1,2349.4,248.6,8440.9,10466.4,368.7,2015.0,8586.8,...,5563.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,2010.0,7997.6,1371.5,2345.0,249.7,8087.0,10148.8,363.5,1894.6,8643.0,...,5348.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,2009.0,8350.0,1445.4,2248.8,289.4,7312.6,9495.2,362.1,1823.0,8816.3,...,5088.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,2008.0,11558.6,1411.4,2254.5,309.8,7348.8,9782.5,344.2,1881.9,9798.4,...,5439.9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,2007.0,12419.5,1628.2,2288.1,370.8,7204.5,9933.5,360.6,1850.9,8888.4,...,5605.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,2006.0,10985.5,1627.4,2317.1,375.6,6616.6,9111.9,326.5,1827.4,7832.8,...,5461.8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,2005.0,9951.9,1797.1,2199.5,382.4,6368.6,8757.5,326.7,1746.3,6694.6,...,4790.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,2004.0,9866.3,1839.2,2119.9,346.4,6245.5,8428.6,336.7,1758.7,6643.2,...,4387.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,2003.0,9223.2,1659.3,2082.4,339.0,5967.2,8288.9,317.9,1716.3,6221.3,...,4205.7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,2002.0,8302.9,1700.0,1903.5,332.8,5584.6,8006.7,383.2,1636.5,7031.6,...,3981.8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,2001.0,7758.1,1634.0,1759.0,326.7,5139.6,7556.8,374.4,1600.9,7435.5,...,3701.3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,2000.0,6521.8,1578.1,1717.2,298.9,4755.4,7688.5,364.0,1726.1,6627.6,...,3383.9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,1999.0,6058.4,1439.6,1689.8,299.2,4790.1,7870.2,318.9,1651.5,6985.1,...,2974.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
columns_to_drop = df_2.columns[15:24]

In [7]:
df_3 = df_2.drop(columns=columns_to_drop, axis=1)

In [8]:
df_3

,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17
3,2022.0,8135.1,2194.4,3158.7,407.2,12100.7,15308.3,552.4,2414.0,12586.6,7192.3,4900.0,1514.7,4338.0,7399.4
4,2021.0,8440.5,2077.5,3111.5,396.7,13349.0,14768.3,592.9,2344.5,11319.0,6718.8,4538.8,1532.5,3079.1,10006.7
5,2020.0,7397.3,1886.9,2778.2,392.8,12278.7,14168.0,523.4,2254.6,11799.4,6219.9,4957.3,1391.9,2689.8,8943.1
6,2019.0,7139.2,1795.5,2704.9,408.1,11763.4,13882.4,543.0,2371.9,11464.7,6149.8,4304.9,1393.9,2437.6,8336.4
7,2018.0,7124.5,1821.2,2773.4,379.9,11663.0,14017.0,558.4,2236.8,12212.8,6281.9,4193.2,1372.9,2420.6,8224.2
8,2017.0,7363.3,1847.8,2669.9,382.3,11070.2,13606.2,550.8,2276.2,11854.3,6399.9,4111.9,1454.2,2250.1,8234.0
9,2016.0,7336.2,1824.8,2585.0,395.6,10588.4,13249.5,517.9,2235.8,10994.5,6198.2,4374.7,1365.8,2432.7,7181.2
10,2015.0,7661.2,1942.8,2525.0,359.3,9733.1,12861.1,510.5,2161.0,10991.5,6017.8,4454.0,1336.7,2396.0,6721.6
11,2014.0,7232.6,1720.2,2474.2,302.5,9574.5,12161.7,476.2,2112.4,11364.5,7507.7,4268.5,1296.1,2459.4,6226.6
12,2013.0,6947.3,1400.5,2399.7,293.6,8989.3,11833.3,433.6,2087.0,13034.1,6278.5,4048.2,1303.6,2342.7,5946.4
13,2012.0,7909.8,1336.6,2384.4,292.0,8628.1,11031.8,478.0,2018.8,10689.8,5012.8,4119.3,1237.4,2258.9,5991.0
14,2011.0,7872.7,1270.1,2349.4,248.6,8440.9,10466.4,368.7,2015.0,8586.8,5229.4,4569.6,1313.0,2222.3,5563.5
15,2010.0,7997.6,1371.5,2345.0,249.7,8087.0,10148.8,363.5,1894.6,8643.0,4583.6,4003.4,1222.2,2027.7,5348.6
16,2009.0,8350.0,1445.4,2248.8,289.4,7312.6,9495.2,362.1,1823.0,8816.3,4435.7,3457.5,1169.4,1839.3,5088.2
17,2008.0,11558.6,1411.4,2254.5,309.8,7348.8,9782.5,344.2,1881.9,9798.4,4839.0,3666.1,1114.2,2080.3,5439.9
18,2007.0,12419.5,1628.2,2288.1,370.8,7204.5,9933.5,360.6,1850.9,8888.4,3930.4,2985.5,1129.2,1996.9,5605.1
19,2006.0,10985.5,1627.4,2317.1,375.6,6616.6,9111.9,326.5,1827.4,7832.8,3576.7,3916.2,1255.6,1955.3,5461.8
20,2005.0,9951.9,1797.1,2199.5,382.4,6368.6,8757.5,326.7,1746.3,6694.6,2869.0,3125.6,1308.1,1832.5,4790.1
21,2004.0,9866.3,1839.2,2119.9,346.4,6245.5,8428.6,336.7,1758.7,6643.2,2759.4,2433.1,1170.3,1750.1,4387.6
22,2003.0,9223.2,1659.3,2082.4,339.0,5967.2,8288.9,317.9,1716.3,6221.3,2066.7,2416.7,1048.5,1532.9,4205.7
23,2002.0,8302.9,1700.0,1903.5,332.8,5584.6,8006.7,383.2,1636.5,7031.6,2380.2,2193.6,918.6,1502.9,3981.8
24,2001.0,7758.1,1634.0,1759.0,326.7,5139.6,7556.8,374.4,1600.9,7435.5,2803.1,2085.7,993.1,1403.4,3701.3
25,2000.0,6521.8,1578.1,1717.2,298.9,4755.4,7688.5,364.0,1726.1,6627.6,2802.1,2159.0,1001.2,1168.1,3383.9
26,1999.0,6058.4,1439.6,1689.8,299.2,4790.1,7870.2,318.9,1651.5,6985.1,2428.0,2269.3,924.7,1099.2,2974.1

In [9]:
#remane the columns
df_4 = df_3.rename(columns={3: 'Years', 4:'Live meat animals', 5: 'Meats', 6: 'Fish and shellfish ', 7:'Dairy', 8: 'Vegetables',
                            9: 'Fruits',10: 'Nuts',11: 'Coffee, tea, and spices',12: 'Grains',13: 'Vegetable oils',14: 'Sugar and candy', 
                           15: 'Cocoa and chocolate',16: 'Other edible products',17: 'Beverages'})
df_4

,Years,Live meat animals,Meats,Fish and shellfish,Dairy,Vegetables,Fruits,Nuts,"Coffee, tea, and spices",Grains,Vegetable oils,Sugar and candy,Cocoa and chocolate,Other edible products,Beverages
3,2022.0,8135.1,2194.4,3158.7,407.2,12100.7,15308.3,552.4,2414.0,12586.6,7192.3,4900.0,1514.7,4338.0,7399.4
4,2021.0,8440.5,2077.5,3111.5,396.7,13349.0,14768.3,592.9,2344.5,11319.0,6718.8,4538.8,1532.5,3079.1,10006.7
5,2020.0,7397.3,1886.9,2778.2,392.8,12278.7,14168.0,523.4,2254.6,11799.4,6219.9,4957.3,1391.9,2689.8,8943.1
6,2019.0,7139.2,1795.5,2704.9,408.1,11763.4,13882.4,543.0,2371.9,11464.7,6149.8,4304.9,1393.9,2437.6,8336.4
7,2018.0,7124.5,1821.2,2773.4,379.9,11663.0,14017.0,558.4,2236.8,12212.8,6281.9,4193.2,1372.9,2420.6,8224.2
8,2017.0,7363.3,1847.8,2669.9,382.3,11070.2,13606.2,550.8,2276.2,11854.3,6399.9,4111.9,1454.2,2250.1,8234.0
9,2016.0,7336.2,1824.8,2585.0,395.6,10588.4,13249.5,517.9,2235.8,10994.5,6198.2,4374.7,1365.8,2432.7,7181.2
10,2015.0,7661.2,1942.8,2525.0,359.3,9733.1,12861.1,510.5,2161.0,10991.5,6017.8,4454.0,1336.7,2396.0,6721.6
11,2014.0,7232.6,1720.2,2474.2,302.5,9574.5,12161.7,476.2,2112.4,11364.5,7507.7,4268.5,1296.1,2459.4,6226.6
12,2013.0,6947.3,1400.5,2399.7,293.6,8989.3,11833.3,433.6,2087.0,13034.1,6278.5,4048.2,1303.6,2342.7,5946.4
13,2012.0,7909.8,1336.6,2384.4,292.0,8628.1,11031.8,478.0,2018.8,10689.8,5012.8,4119.3,1237.4,2258.9,5991.0
14,2011.0,7872.7,1270.1,2349.4,248.6,8440.9,10466.4,368.7,2015.0,8586.8,5229.4,4569.6,1313.0,2222.3,5563.5
15,2010.0,7997.6,1371.5,2345.0,249.7,8087.0,10148.8,363.5,1894.6,8643.0,4583.6,4003.4,1222.2,2027.7,5348.6
16,2009.0,8350.0,1445.4,2248.8,289.4,7312.6,9495.2,362.1,1823.0,8816.3,4435.7,3457.5,1169.4,1839.3,5088.2
17,2008.0,11558.6,1411.4,2254.5,309.8,7348.8,9782.5,344.2,1881.9,9798.4,4839.0,3666.1,1114.2,2080.3,5439.9
18,2007.0,12419.5,1628.2,2288.1,370.8,7204.5,9933.5,360.6,1850.9,8888.4,3930.4,2985.5,1129.2,1996.9,5605.1
19,2006.0,10985.5,1627.4,2317.1,375.6,6616.6,9111.9,326.5,1827.4,7832.8,3576.7,3916.2,1255.6,1955.3,5461.8
20,2005.0,9951.9,1797.1,2199.5,382.4,6368.6,8757.5,326.7,1746.3,6694.6,2869.0,3125.6,1308.1,1832.5,4790.1
21,2004.0,9866.3,1839.2,2119.9,346.4,6245.5,8428.6,336.7,1758.7,6643.2,2759.4,2433.1,1170.3,1750.1,4387.6
22,2003.0,9223.2,1659.3,2082.4,339.0,5967.2,8288.9,317.9,1716.3,6221.3,2066.7,2416.7,1048.5,1532.9,4205.7
23,2002.0,8302.9,1700.0,1903.5,332.8,5584.6,8006.7,383.2,1636.5,7031.6,2380.2,2193.6,918.6,1502.9,3981.8
24,2001.0,7758.1,1634.0,1759.0,326.7,5139.6,7556.8,374.4,1600.9,7435.5,2803.1,2085.7,993.1,1403.4,3701.3
25,2000.0,6521.8,1578.1,1717.2,298.9,4755.4,7688.5,364.0,1726.1,6627.6,2802.1,2159.0,1001.2,1168.1,3383.9
26,1999.0,6058.4,1439.6,1689.8,299.2,4790.1,7870.2,318.9,1651.5,6985.1,2428.0,2269.3,924.7,1099.2,2974.1

In [10]:
# Assuming df is your DataFrame and 'Years' is the column containing values like "1999.0"

df_4['Years'] = df_4['Years'].astype(str).str.replace('.0', '').astype(int)
df_4['Years'] = df_4['Years'].astype(object)

In [11]:
df_4

,Years,Live meat animals,Meats,Fish and shellfish,Dairy,Vegetables,Fruits,Nuts,"Coffee, tea, and spices",Grains,Vegetable oils,Sugar and candy,Cocoa and chocolate,Other edible products,Beverages
3,2022,8135.1,2194.4,3158.7,407.2,12100.7,15308.3,552.4,2414.0,12586.6,7192.3,4900.0,1514.7,4338.0,7399.4
4,2021,8440.5,2077.5,3111.5,396.7,13349.0,14768.3,592.9,2344.5,11319.0,6718.8,4538.8,1532.5,3079.1,10006.7
5,2020,7397.3,1886.9,2778.2,392.8,12278.7,14168.0,523.4,2254.6,11799.4,6219.9,4957.3,1391.9,2689.8,8943.1
6,2019,7139.2,1795.5,2704.9,408.1,11763.4,13882.4,543.0,2371.9,11464.7,6149.8,4304.9,1393.9,2437.6,8336.4
7,2018,7124.5,1821.2,2773.4,379.9,11663.0,14017.0,558.4,2236.8,12212.8,6281.9,4193.2,1372.9,2420.6,8224.2
8,2017,7363.3,1847.8,2669.9,382.3,11070.2,13606.2,550.8,2276.2,11854.3,6399.9,4111.9,1454.2,2250.1,8234.0
9,2016,7336.2,1824.8,2585.0,395.6,10588.4,13249.5,517.9,2235.8,10994.5,6198.2,4374.7,1365.8,2432.7,7181.2
10,2015,7661.2,1942.8,2525.0,359.3,9733.1,12861.1,510.5,2161.0,10991.5,6017.8,4454.0,1336.7,2396.0,6721.6
11,2014,7232.6,1720.2,2474.2,302.5,9574.5,12161.7,476.2,2112.4,11364.5,7507.7,4268.5,1296.1,2459.4,6226.6
12,2013,6947.3,1400.5,2399.7,293.6,8989.3,11833.3,433.6,2087.0,13034.1,6278.5,4048.2,1303.6,2342.7,5946.4
13,2012,7909.8,1336.6,2384.4,292.0,8628.1,11031.8,478.0,2018.8,10689.8,5012.8,4119.3,1237.4,2258.9,5991.0
14,2011,7872.7,1270.1,2349.4,248.6,8440.9,10466.4,368.7,2015.0,8586.8,5229.4,4569.6,1313.0,2222.3,5563.5
15,2010,7997.6,1371.5,2345.0,249.7,8087.0,10148.8,363.5,1894.6,8643.0,4583.6,4003.4,1222.2,2027.7,5348.6
16,2009,8350.0,1445.4,2248.8,289.4,7312.6,9495.2,362.1,1823.0,8816.3,4435.7,3457.5,1169.4,1839.3,5088.2
17,2008,11558.6,1411.4,2254.5,309.8,7348.8,9782.5,344.2,1881.9,9798.4,4839.0,3666.1,1114.2,2080.3,5439.9
18,2007,12419.5,1628.2,2288.1,370.8,7204.5,9933.5,360.6,1850.9,8888.4,3930.4,2985.5,1129.2,1996.9,5605.1
19,2006,10985.5,1627.4,2317.1,375.6,6616.6,9111.9,326.5,1827.4,7832.8,3576.7,3916.2,1255.6,1955.3,5461.8
20,2005,9951.9,1797.1,2199.5,382.4,6368.6,8757.5,326.7,1746.3,6694.6,2869.0,3125.6,1308.1,1832.5,4790.1
21,2004,9866.3,1839.2,2119.9,346.4,6245.5,8428.6,336.7,1758.7,6643.2,2759.4,2433.1,1170.3,1750.1,4387.6
22,2003,9223.2,1659.3,2082.4,339.0,5967.2,8288.9,317.9,1716.3,6221.3,2066.7,2416.7,1048.5,1532.9,4205.7
23,2002,8302.9,1700.0,1903.5,332.8,5584.6,8006.7,383.2,1636.5,7031.6,2380.2,2193.6,918.6,1502.9,3981.8
24,2001,7758.1,1634.0,1759.0,326.7,5139.6,7556.8,374.4,1600.9,7435.5,2803.1,2085.7,993.1,1403.4,3701.3
25,2000,6521.8,1578.1,1717.2,298.9,4755.4,7688.5,364.0,1726.1,6627.6,2802.1,2159.0,1001.2,1168.1,3383.9
26,1999,6058.4,1439.6,1689.8,299.2,4790.1,7870.2,318.9,1651.5,6985.1,2428.0,2269.3,924.7,1099.2,2974.1

In [12]:
df_4.to_csv('volume_usfoodimport.csv')